# + -------------------------------------------------------------------------------- + #
# | BOT SETTINGS ( 봇 설정 )
# + -------------------------------------------------------------------------------- + #
# 봇 토큰
BOT_TOKEN: "MTAzMzU4MDI1NjMxOTI1NDU1OQ.GsxNar.rg8zb61auGEasp9au4S0ueI9RwF8EdUCu3C_y4"
# 감사로그 채널 ID
AUDIT_LOG_CHANNEL_ID: '1157604707372646410'

# + -------------------------------------------------------------------------------- + #
# | ACTIVITY SETTINGS ( 활동 설정 )
# + -------------------------------------------------------------------------------- + #
# 봇 상태 메시지
ACTIVITY_NAME: "https://starly.kr"
# 봇 활동 타입
ACTIVITY_TYPE: "playing"
# 봇 상태
STATUS: "ONLINE"

# + -------------------------------------------------------------------------------- + #
# | DISCORD SETTINGS ( 디스코드 설정 )
# + -------------------------------------------------------------------------------- + #
# 서버 아이디
GUILD_ID: "1112484864344719522"
# 관리자 역할
ADMIN_ROLE: "1141626734664482907"

# + -------------------------------------------------------------------------------- + #
# | EMBED COLORS ( 임베드 색상 설정 )
# + -------------------------------------------------------------------------------- + #
# 기본 색상
EMBED_COLOR: "#fbb500"
# 성공 색상
EMBED_COLOR_SUCCESS: "#7eff8e"
# 오류 색상
EMBED_COLOR_ERROR: "#ff4b4b"

# + -------------------------------------------------------------------------------- + #
# | DATABASE CONFIGURATION ( 데이터베이스 설정 )
# + -------------------------------------------------------------------------------- + #
DB_HOST: "mongodb://localhost:27017"
DB_DATABASE: "StarlyBot"
DB_COLLECTION_USER: "user"
DB_COLLECTION_PLUGIN: "plugin"
DB_COLLECTION_TICKET: "ticket"
DB_COLLECTION_WARN: "warn"
DB_COLLECTION_SHORTEN_LINK: "shortenLink"
DB_COLLECTION_BLACKLIST: "blacklist"

# + -------------------------------------------------------------------------------- + #
# | WEB SERVER CONFIGURATION ( 웹 서버 설정 )
# + -------------------------------------------------------------------------------- + #
# 공통된 웹 주소
WEB_ADDRESS: "59.4.140.144"
# 인증 서버 포트
WEB_PORT: 8080

# + -------------------------------------------------------------------------------- + #
# | AUTH SETTINGS ( 인증 설정 )
# + -------------------------------------------------------------------------------- + #
# 인증 후, 지급되는 역할
AUTH_ROLE: "1112485200933425272"

# + -------------------------------------------------------------------------------- + #
# | WARN SETTINGS ( 경고 설정 )
# + -------------------------------------------------------------------------------- + #
WARN_CHANNEL_ID: "1158149720577953842"

# + -------------------------------------------------------------------------------- + #
# | TICKET SETTINGS ( 티켓 설정 )
# + -------------------------------------------------------------------------------- + #
TICKET_CATEGORY_ID: "1147915215128768542"
TICKET_CHANNEL_ID: "1147915298628980879"

# + -------------------------------------------------------------------------------- + #
# | PLUGIN MANAGEMENT SETTINGS ( 플러그인 관리 설정 )
# + -------------------------------------------------------------------------------- + #
CHANNEL_ID_PLUGIN_MANAGEMENT: "1148012770520989836"
FREE_PLUGIN_FORUM: "1147998082336825515"
PREMIUM_PLUGIN_FORUM: "1147998042985865216"
RELEASE_NOTICE_CHANNEL: "1148487084626169906"

# + -------------------------------------------------------------------------------- + #
# | CF IMAGES CONFIGURATION ( 클라우드플레어 Images 설정 )
# + -------------------------------------------------------------------------------- + #
ACCOUNT_ID: "e644175af98fbd1549cea8ffd512536d"
ACCOUNT_HASH: "zI1a4o7oosLEca8Wq4ML6w"
API_TOKEN: "eQm1CexVtGxNf9mXueVGBhRLT4_1Mdang_JcrDj-"