# + -------------------------------------------------------------------------------- + #
# | BOT SETTINGS ( 봇 설정 )
# + -------------------------------------------------------------------------------- + #
# 봇 토큰
BOT_TOKEN: "MTAzMzU4MDI1NjMxOTI1NDU1OQ.GsxNar.rg8zb61auGEasp9au4S0ueI9RwF8EdUCu3C_y4"

# + -------------------------------------------------------------------------------- + #
# | ACTIVITY SETTINGS ( 활동 설정 )
# + -------------------------------------------------------------------------------- + #
# 봇 상태 메시지
ACTIVITY_NAME: "https://starly.kr"
# 봇 활동 타입
ACTIVITY_TYPE: "playing"
# 봇 상태
STATUS: "ONLINE"

# + -------------------------------------------------------------------------------- + #
# | DISCORD SETTINGS ( 디스코드 설정 )
# + -------------------------------------------------------------------------------- + #
# 서버 아이디
GUILD_ID: "1112484864344719522"
# 관리자 역할
ADMIN_ROLE: "1141626734664482907"

# + -------------------------------------------------------------------------------- + #
# | EMBED COLORS ( 임베드 색상 설정 )
# + -------------------------------------------------------------------------------- + #
# 기본 색상
EMBED_COLOR: "#fbb500"
# 성공 색상
EMBED_COLOR_SUCCESS: "#7eff8e"
# 오류 색상
EMBED_COLOR_ERROR: "#ff4b4b"

# + -------------------------------------------------------------------------------- + #
# | DATABASE CONFIGURATION ( 데이터베이스 설정 )
# + -------------------------------------------------------------------------------- + #
DB_HOST: "mongodb://localhost:27017"
DB_DATABASE: "StarlyBot"
DB_COLLECTION_USER: "user"
DB_COLLECTION_PLUGIN: "plugin"
DB_COLLECTION_TICKET: "ticket"

# + -------------------------------------------------------------------------------- + #
# | AUTHENTICATION CONFIGURATION ( 인증 설정 )
# + -------------------------------------------------------------------------------- + #
AUTH_LINK: "http://59.4.140.144"
AUTH_PORT: 8080
AUTH_ROLE: "1112485200933425272"

# + -------------------------------------------------------------------------------- + #
# | PREMIUM SETTINGS ( 프리미엄 설정 )
# + -------------------------------------------------------------------------------- + #
PREMIUM_CATEGORY_ID: "1141704277392375918"

# + -------------------------------------------------------------------------------- + #
# | TICKET PATH ( 티켓 경로 )
# + -------------------------------------------------------------------------------- + #
TICKET_PATH: "D:\\Project\\Starly\\StarlyBot\\bot\\tickets\\"